services:
  - type: web
    name: phase-one-capstone-project
    env: static
    staticPublishPath: ./Html
    routes:
      - type: rewrite
        source: /css/*
        destination: /css/:splat
      - type: rewrite
        source: /Asset/*
        destination: /Asset/:splat
      - type: rewrite
        source: /image/*
        destination: /image/:splat
